# -*- coding: utf-8 -*-
"""MEDISCI

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DJpBcu30dLTGnNPY7D3FV9Cdmt2peYiM
"""

!pip install streamlit pyngrok pandas numpy scikit-learn plotly opencv-python pillow tensorflow

from google.colab import files
uploaded = files.upload()

from google.colab import files
files.upload()

import os
os.listdir()

import pandas as pd
from sklearn.preprocessing import MultiLabelBinarizer
from sklearn.ensemble import RandomForestClassifier

# Load main dataset
df = pd.read_csv("dataset.csv")

# Combine symptom columns
symptom_cols = df.columns[1:]
df["symptoms"] = df[symptom_cols].values.tolist()

# Remove NaN
df["symptoms"] = df["symptoms"].apply(
    lambda x: [str(i) for i in x if str(i) != "nan"]
)

# Convert to numeric
mlb = MultiLabelBinarizer()
X = mlb.fit_transform(df["symptoms"])
y = df["Disease"]

# Train model
model = RandomForestClassifier()
model.fit(X, y)

all_symptoms = list(mlb.classes_)

print("✅ Disease model ready")

# Severity
severity_df = pd.read_csv("Symptom-severity.csv")
severity_dict = dict(zip(severity_df.iloc[:,0], severity_df.iloc[:,1]))

# Description
desc_df = pd.read_csv("symptom_Description.csv")
desc_dict = dict(zip(desc_df.iloc[:,0], desc_df.iloc[:,1]))

# Precautions
prec_df = pd.read_csv("symptom_precaution.csv")

prec_dict = {}
for i in range(len(prec_df)):
    disease = prec_df.iloc[i,0]
    prec_dict[disease] = list(prec_df.iloc[i,1:].dropna())

print("✅ Extra datasets loaded")

drug_df = pd.read_csv("drug_interactions.csv")

# Convert to lowercase
drug_df["Drug1"] = drug_df["Drug1"].str.lower()
drug_df["Drug2"] = drug_df["Drug2"].str.lower()

print("✅ Drug dataset ready")

def predict_disease(selected_symptoms):
    input_data = [0] * len(all_symptoms)

    for s in selected_symptoms:
        if s in all_symptoms:
            input_data[all_symptoms.index(s)] = 1

    return model.predict([input_data])[0]

def calculate_risk(symptoms):
    score = sum(severity_dict.get(s, 1) for s in symptoms)
    return round((score / (len(symptoms)*5)) * 100, 2) if symptoms else 0

def get_description(disease):
    return desc_dict.get(disease, "No description available")

def get_precautions(disease):
    return prec_dict.get(disease, ["No precautions available"])

def check_drug(d1, d2):
    d1, d2 = d1.lower(), d2.lower()

    res = drug_df[
        ((drug_df["Drug1"] == d1) & (drug_df["Drug2"] == d2)) |
        ((drug_df["Drug1"] == d2) & (drug_df["Drug2"] == d1))
    ]

    if not res.empty:
        return res.iloc[0].to_dict()
    else:
        return {
            "Drug1": d1,
            "Drug2": d2,
            "Severity": "Safe",
            "Interaction": "No known interaction"
        }

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import streamlit as st
# import pandas as pd
# import numpy as np
# import plotly.express as px
# from sklearn.preprocessing import MultiLabelBinarizer
# from sklearn.ensemble import RandomForestClassifier
# 
# st.set_page_config(page_title="MediSense AI", layout="wide")
# 
# # ---------------- LOAD & TRAIN MODEL ----------------
# 
# @st.cache_resource
# def load_model():
# 
#     df = pd.read_csv("dataset.csv")
# 
#     symptom_cols = df.columns[1:]
# 
#     df["symptoms"] = df[symptom_cols].values.tolist()
# 
#     df["symptoms"] = df["symptoms"].apply(
#         lambda x: [str(i) for i in x if str(i) != "nan"]
#     )
# 
#     mlb = MultiLabelBinarizer()
# 
#     X = mlb.fit_transform(df["symptoms"])
#     y = df["Disease"]
# 
#     model = RandomForestClassifier(n_estimators=150)
#     model.fit(X, y)
# 
#     all_symptoms = list(mlb.classes_)
# 
#     return model, all_symptoms
# 
# model, all_symptoms = load_model()
# 
# # ---------------- LOAD DATASETS ----------------
# 
# @st.cache_data
# def load_data():
# 
#     severity_df = pd.read_csv("Symptom-severity.csv")
#     severity_dict = dict(zip(severity_df.iloc[:,0], severity_df.iloc[:,1]))
# 
#     desc_df = pd.read_csv("symptom_Description.csv")
#     desc_dict = dict(zip(desc_df.iloc[:,0], desc_df.iloc[:,1]))
# 
#     prec_df = pd.read_csv("symptom_precaution.csv")
# 
#     prec_dict = {}
# 
#     for i in range(len(prec_df)):
#         disease = prec_df.iloc[i,0]
#         prec_dict[disease] = list(prec_df.iloc[i,1:].dropna())
# 
#     drug_df = pd.read_csv("drug_interactions.csv")
#     drug_df["Drug1"] = drug_df["Drug1"].str.lower()
#     drug_df["Drug2"] = drug_df["Drug2"].str.lower()
# 
#     return severity_dict, desc_dict, prec_dict, drug_df
# 
# severity_dict, desc_dict, prec_dict, drug_df = load_data()
# 
# # ---------------- FUNCTIONS ----------------
# 
# def predict_disease(symptoms):
# 
#     input_data = [0]*len(all_symptoms)
# 
#     for s in symptoms:
#         if s in all_symptoms:
#             input_data[all_symptoms.index(s)] = 1
# 
#     return model.predict([input_data])[0]
# 
# 
# def calculate_risk(symptoms):
# 
#     score = sum(severity_dict.get(s,1) for s in symptoms)
# 
#     if len(symptoms)==0:
#         return 0
# 
#     risk = (score/(len(symptoms)*5))*100
#     return round(risk,2)
# 
# 
# def get_description(disease):
#     return desc_dict.get(disease,"No description available")
# 
# 
# def get_precautions(disease):
#     return prec_dict.get(disease,["No precautions available"])
# 
# 
# def check_drug(d1,d2):
# 
#     d1=d1.lower()
#     d2=d2.lower()
# 
#     res = drug_df[
#         ((drug_df["Drug1"]==d1)&(drug_df["Drug2"]==d2)) |
#         ((drug_df["Drug1"]==d2)&(drug_df["Drug2"]==d1))
#     ]
# 
#     if not res.empty:
#         return res.iloc[0].to_dict()
# 
#     return {
#         "Drug1":d1,
#         "Drug2":d2,
#         "Interaction":"No known interaction",
#         "Severity":"Safe"
#     }
# 
# # ---------------- UI ----------------
# 
# st.title("🩺 MediSense AI")
# st.write("AI Powered Medical Assistant")
# 
# menu = st.sidebar.selectbox(
#     "Navigation",
#     ["Symptom Checker","Medication Safety"]
# )
# 
# # -------- Symptom Checker --------
# 
# if menu=="Symptom Checker":
# 
#     st.header("🧠 Disease Prediction")
# 
#     symptoms = st.multiselect(
#         "Select Symptoms",
#         all_symptoms
#     )
# 
#     if st.button("Analyze"):
# 
#         if symptoms:
# 
#             disease = predict_disease(symptoms)
#             risk = calculate_risk(symptoms)
# 
#             st.success(f"Predicted Disease: {disease}")
#             st.metric("Risk Score",f"{risk}%")
# 
#             st.subheader("📖 Description")
#             st.write(get_description(disease))
# 
#             st.subheader("💊 Precautions")
#             for p in get_precautions(disease):
#                 st.write(f"✔ {p}")
# 
#             chart = px.bar(
#                 x=["Risk Level"],
#                 y=[risk],
#                 labels={"x":"","y":"Risk %"},
#                 title="Health Risk Indicator"
#             )
# 
#             st.plotly_chart(chart, use_container_width=True)
# 
#         else:
#             st.warning("Select symptoms")
# 
# # -------- Drug Checker --------
# 
# elif menu=="Medication Safety":
# 
#     st.header("💊 Drug Interaction Checker")
# 
#     drug1 = st.text_input("Drug 1")
#     drug2 = st.text_input("Drug 2")
# 
#     if st.button("Check Interaction"):
# 
#         if drug1 and drug2:
# 
#             result = check_drug(drug1,drug2)
# 
#             st.write("Drug 1:",result["Drug1"])
#             st.write("Drug 2:",result["Drug2"])
#             st.write("Interaction:",result["Interaction"])
#             st.write("Severity:",result["Severity"])
# 
#             if result["Severity"]=="High":
#                 st.error("⚠ High Risk")
#             elif result["Severity"]=="Medium":
#                 st.warning("⚠ Moderate Risk")
#             else:
#                 st.success("✅ Safe")
# 
#         else:
#             st.info("Enter both drugs")

import subprocess
import time

# Start Streamlit in background
process = subprocess.Popen(
    ["streamlit", "run", "app.py", "--server.port", "8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT
)

# Wait a few seconds for Streamlit to start
time.sleep(5)

# Download Cloudflare Tunnel
!wget -q -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
!chmod +x cloudflared

# Start Cloudflare Tunnel
tunnel = subprocess.Popen(
    ["./cloudflared", "tunnel", "--url", "http://localhost:8501"],
    stdout=subprocess.PIPE,
    stderr=subprocess.STDOUT
)

# Print the public URL once it appears
import re

for line in tunnel.stdout:
    line = line.decode()
    if "trycloudflare.com" in line:
        match = re.search(r"(https://[-a-z0-9]+\.trycloudflare\.com)", line)
        if match:
            print("🌐 Your MediSense AI Link:", match.group(1))
            break